name: CI- Node.js Express App

on:
    push:
        branches:
            - main

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install Dependencies
              run : npm install

            - name:  Build project
              run: npm run build   
            
            - name: Start Server
              run: npm run dev
